### ISSUE TITLE
Save the failing/optimal sequences of transactions in a special "reproducers" directory

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/medusa#114]
When medusa detects a failing sequence of transactions that produces a failure (e.g. assertion) or reaches a maximum value at end of the optimization campaign, it should save these inside a "reproducers" directory created inside the corpus one.

**Comment by ggrieco-tob** [comment]
Is this already fixed? can we close it?

**Comment by Xenomega** [comment]
Yes, good catch, closed with #111
