### ISSUE TITLE
Feat: support fuzzing-templates

### ISSUE THREAD

**Issue by sambacha** [crytic/medusa#126]
Fuzzing templates can help assist narrowing down search space, provide for rewriting functions that are not easily tested, etc. similar to how protobuf specs can be used to assist in fuzzing.

Re:
https://github.com/projectdiscovery/fuzzing-templates

**Comment by ggrieco-tob** [comment]
This looks somehow related to https://github.com/crytic/properties. Since the properties are in Solidity, they don't need to be particularly tied to any fuzzer.

**Comment by sambacha** [comment]
> This looks somehow related to https://github.com/crytic/properties. Since the properties are in Solidity, they don't need to be particularly tied to any fuzzer.

Yes, yes this looks like it will do nicely.

What else yall got?

Thanks 🍻

**Comment by ggrieco-tob** [comment]
Not sure exactly what other type of "templates" you need. Can you give a concrete example so we can move forward?

**Comment by anishnaik** [comment]
Due to lack of activity, closing this issue.
