### ISSUE TITLE
Feature Request: Event decoding

### ISSUE THREAD

**Issue by rappie** [crytic/medusa#130]
Currently an event is logged like this:

```
-> [event] <unresolved(topics=[7cdb51e9dbbc205231228146c3246e7f914aa6d4a33170e43ecc8e3593481d1a], data=000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000064265766572730000000000000000000000000000000000000000000000000000)>
```

For debugging purposes it would be nice to have the decoded information, like:
```
Debug("this is a debug message")
```

**Comment by anishnaik** [comment]
Hey @rappie , this should only happen if we failed to decode the error properly, which should not happen tbh. Do you mind posting some example code so that I can test this out and see if there is a bug on our side?

**Comment by Xenomega** [comment]
This could happen if the string is indexed. If I remember correctly, indexed strings cannot be loaded from an event in some scenarios.

In the event data you posted, the string you logged is not visible in the topics/data, so I suspect that's may be what's happening?

**Comment by anishnaik** [comment]
Thanks @rappie , this looks like a bug

tracking here: https://github.com/crytic/medusa/issues/131
