### ISSUE TITLE
Feature Request: Shrinking argument values

### ISSUE THREAD

**Issue by rappie** [crytic/medusa#136]
It would be nice if all argument values were shrunk.

This is especially helpful when using helper functions that do modulo operations so you'll end up knowing the real value used after it has been shrunk enough.

**Comment by Xenomega** [comment]
Context for developers:
- The entry point for shrinking call sequences is the `shrinkCallSequence` method within [FuzzerWorker](https://github.com/crytic/medusa/blob/master/fuzzing/fuzzer_worker.go).
  - This currently tries deleting every call in the call sequence it can, and re-testing it.
  - We will want to add functionality that intermittently tries to shrink values, then delete some calls when it was able to, then continue shrinking for some number of iterations
  - The number of iterations to shrink for should be configurable to allow shrinking of many common failed test scenario's call sequences in a reasonable time.
- The actual shrinking will need to be implemented in `fuzzing/valuegeneration/*`. You will likely be editing `abi_values.go` as well as the value generator files themselves.
  - You may want to make new code paths for this in the value generator itself at least, so it will optimally choose mutation operations that only decrease the size of some variables in different ways.

**Comment by ggrieco-tob** [comment]
I already started this, I should have a draft PR with some code tomorrow

**Comment by anishnaik** [comment]
This issue has been resolved. Closing.
