### ISSUE TITLE
Improve config option parity between medusa and echidna

### ISSUE THREAD

**Issue by anishnaik** [crytic/medusa#140]
There are probably a few configuration options that echidna has that we can implement in medusa with low/medium effort. Thus, the following is required to close this issue:
- [ ] Identify the low-hanging config options that can be implemented in medusa
- [ ] implement those config options, obviously
- [ ] test them correctly to ensure that they work just like in echidna.

**Comment by ahpaleus** [comment]
This issue might be helpful: https://github.com/crytic/medusa/issues/89

**Comment by anishnaik** [comment]
Closing in preference of #89
