### ISSUE TITLE
Extend assertion-testing with different panic codes

### ISSUE THREAD

**Issue by Xenomega** [crytic/medusa#142]
Currently, the assertion testing provider only triggers a failed assertion if the panic code is `AssertFailed` (indicating an actual Solidity `assert(...)` statement panicked).

We should extend the `AssertionTestingConfig` to also have boolean options for other types of panics, such as overflows. By default, these extended options should be disabled so only `AssertFailed` is enabled by default. We should also add a config option for `AssertFailed` itself, e.g. if someone wants to only test overflows.

References:
- [Assertion-testing logic](https://github.com/crytic/medusa/blob/b7ea61bd76cbdb0520a5c4d34c7f1a8dc139f54e/fuzzing/test_case_assertion_provider.go#L76) (to be changed)
- [Solidity panic codes](https://github.com/crytic/medusa/blob/b7ea61bd76cbdb0520a5c4d34c7f1a8dc139f54e/compilation/abiutils/solidity_errors.go) (to be leveraged)

TODOs:
- Update `config.go` and `config_defaults.go` with the new config options.
- Update `assertion_test_case_provider.go` in the spot linked above, to check the `Fuzzer`'s config for these options and perform the appropriate checks there.
- Add unit tests to `fuzzer_test.go` to test the different panic conditions enabled/disabled working accordingly.

**Comment by anishnaik** [comment]
This issue has been resolved. Closing.
