### ISSUE TITLE
Feature request: Add `output type` flag to CLI

### ISSUE THREAD

**Issue by damilolaedwards** [crytic/medusa#144]
Currently there's no way to specify the preferred output format when running the fuzzer on CLI, this feature should allow users pass a flag option for the output format. 
Possible options (txt, html, *json...)

**Comment by anishnaik** [comment]
@damilolaedwards i'm going to close this issue. Currently, we allow users to log to file in json output format. They can also pipe non-colorized output which is effectively txt. We also have a PR for coverage reports in JSON (#195) so i think that covers a lot of the ground. 

Feel free to open if you disagree.
