### ISSUE TITLE
Medusa needs a command line/config option to better define which contracts are targeted

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/medusa#145]
This issue is related to #132. The use `deploymentOrder` is useful to simplify deployments, but it doesn't allow to specify which contract contains the tests or which contract actually should be called during the campaign. In echidna, we have the ``--contract` command line to specify the contract name (if there are more than one contract) and by default this will be the contract that will have tests and functions to call. I think the same should be implemented in medusa.

**Comment by Xenomega** [comment]
`TestAllContracts` set to `false` should only test `deploymentOrder` contracts (similar to echidna's `--contract`). With #132, the idea would be to filter the called contracts to only `deploymentOrder` contracts too. Which would match echidna's behavior (I believe). Would this then be adequate? Or were you thinking of something more customizable, like allowing you to specify a _different_ list to target for calls/tests?

**Comment by Xenomega** [comment]
Out of curiosity, how is this different than specifying one contract in `deploymentOrder`? Is it because you can deploy multiple contracts in echidna, but only select one for testing?
