### ISSUE TITLE
Clear separation between mutation and generation is needed

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/medusa#148]
Currently, the code that produces mutations is tightly coupled with the value generation. While this is expected since it is used to mutate values from transactions or generate new ones from time to time, it slows down the development of new mutations. Some examples:

* Shrinking: useful for value minimization
* Expansion: useful for function maximization

While it is still possible to disable value generation in a `RandomValueGenerator` class (e.g. #147), ideally, we should have mutations using a different class.

**Comment by Xenomega** [comment]
Completed in #147
