### ISSUE TITLE
Add an option to suppress execution trace

### ISSUE THREAD

**Issue by tarunbhm** [crytic/medusa#149]
For some complex projects with a large call stack, the execution trace of the failing invariants makes the output extremely lengthy. It becomes hard to find failing invariants in between these long traces. It will be beneficial if we can turn off these traces for such projects.

Execution traces should be turned off with the `traceAll` option set to `false`, but it is not working as expected for some projects.

**Comment by anishnaik** [comment]
So just to add more context here `traceAll` is actually supposed to add a trace for _each_ call in a call sequence (cs). So let's say you break an invariant with a cs of length 3. If `traceAll` is true, then there is a trace for each of the calls in the cs
e.g.
```
1. MyContract.FuncOne
  [Execution Trace]
2. MyOtherContract.FuncTwo
  [Execution Trace]
3. FinalContract.FuncThree
[Execution Trace]
```
whereas if `traceAll` is false, only the call to `FinalContract.FuncThree` would have the execution trace attached.

So I think we should extend this issue to:
(1) allow the disabling of traces completely
(2) invite varying levels of verbosity where only calls / events / reverts / etc from the top level call frame are tracked and any additional call frames are ignored.

**Comment by anishnaik** [comment]
Issue #204 should aid in solving this problem.

**Comment by anishnaik** [comment]
Closing in preference of #204
