### ISSUE TITLE
Using `--config` can break `--target` when the directory is relative

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/medusa#170]
Using `--config` in medusa will cause the current directory to be changed, so `--target .` will fail. For instance:

`medusa fuzz --target . --config dir/medusa.json` will use `dir` as a target, instead of the current directory where the command is executed.

**Comment by anishnaik** [comment]
I don't believe that we will be changing this behavior. medusa will continue to change its working directory to wherever the `medusa.json` file is.
