### ISSUE TITLE
Medusa prints color escapes on non-interactive output

### ISSUE THREAD

**Issue by elopez** [crytic/medusa#198]
Even if the output is non-interactive (e.g running `medusa fuzz .... > file.txt`), medusa will still print color escapes, which make the output hard to read on things that are not a terminal (e.g. a text editor). This also makes it annoying if you need to work with the output; e.g. looking for expected string literals may fail because there's unexpected color escapes in the way.

I did not find a way or a flag to disable this behavior.

**Comment by anishnaik** [comment]
Identify a way to check whether a specific `io.Writer`/ terminal supports ANSI codes for Unix systems

**Comment by anishnaik** [comment]
@elopez I am actually going to close this. The way we deal with this is by specifying a `logDirectory` in the `medusa.json` file. If you have a non-nil `logDirectory` then the directory will start getting populated with log files that have the exact same output as the terminal except without any ANSI escape codes. 

Having non-colorized terminal output is something we should have so I will open a separate issue for that.
