### ISSUE TITLE
Crash after medusa run some time 

### ISSUE THREAD

**Issue by yuliyu123** [crytic/medusa#200]
After executing medusa a period of time, the binary process always crash, see logs below:

`⇾ fuzz: elapsed: 20m51s, calls: 48852587 (39261/sec), seq/s: 392, resets/s: 7, coverage: 6
[1]    63153 killed     medusa fuzz --target contracts/ERC20Test.sol --deployment-order MyToken`

**Comment by yuliyu123** [comment]
full console log:
`❯ medusa fuzz --target contracts/ERC20Test.sol --deployment-order MyToken
⇾ Reading the configuration file at: /Users/looperX/Devlop/security/automation/secureum-medusa/medusa.json
⇾ Compiling targets with crytic-compile
⇾ fuzz: elapsed: 0s, calls: 0 (0/sec), seq/s: 0, resets/s: 0, coverage: 6
⇾ Creating 10 workers...
⇾ fuzz: elapsed: 3s, calls: 125002 (41665/sec), seq/s: 417, resets/s: 9, coverage: 6
⇾ fuzz: elapsed: 6s, calls: 248552 (41168/sec), seq/s: 411, resets/s: 6, coverage: 6
⇾ fuzz: elapsed: 9s, calls: 375386 (42277/sec), seq/s: 422, resets/s: 9, coverage: 6
⇾ fuzz: elapsed: 12s, calls: 503356 (42656/sec), seq/s: 426, resets/s: 6, coverage:
...
⇾ fuzz: elapsed: 21m0s, calls: 52696073 (42992/sec), seq/s: 429, resets/s: 8, coverage: 6
[1]    1528 killed     medusa fuzz --target contracts/ERC20Test.sol --deployment-order MyToken
`

OS: Apple M1 Pro, 13.0.1 (22A400)

Last about 21 minutes and this process be killed.

`{
	"fuzzing": {
		"workers": 10,
		"workerResetLimit": 50,
		"timeout": 0,
		"testLimit": 0,
		"callSequenceLength": 100,
		"corpusDirectory": "corpus",
		"coverageEnabled": true,
		"deploymentOrder": [],
		"constructorArgs": {},
		"deployerAddress": "0x30000",
		"senderAddresses": [
			"0x10000",
			"0x20000",
			"0x30000"
		],
		"blockNumberDelayMax": 60480,
		"blockTimestampDelayMax": 604800,
		"blockGasLimit": 125000000,
		"transactionGasLimit": 12500000,
		"testing": {
			"stopOnFailedTest": true,
			"stopOnFailedContractMatching": true,
			"stopOnNoTests": true,
			"testAllContracts": false,
			"traceAll": false,
			"assertionTesting": {
				"enabled": true,
				"testViewMethods": false,
				"assertionModes": {
					"failOnCompilerInsertedPanic": false,
					"failOnAssertion": true,
					"failOnArithmeticUnderflow": false,
					"failOnDivideByZero": false,
					"failOnEnumTypeConversionOutOfBounds": false,
					"failOnIncorrectStorageAccess": false,
					"failOnPopEmptyArray": false,
					"failOnOutOfBoundsArrayAccess": false,
					"failOnAllocateTooMuchMemory": false,
					"failOnCallUninitializedVariable": false
				}
			},
			"propertyTesting": {
				"enabled": true,
				"testPrefixes": [
					"fuzz_"
				]
			},
			"optimizationTesting": {
				"enabled": false,
				"testPrefixes": [
					"optimize_"
				]
			}
		},
		"chainConfig": {
			"codeSizeCheckDisabled": true,
			"cheatCodes": {
				"cheatCodesEnabled": true,
				"enableFFI": false
			}
		}
	},
	"compilation": {
		"platform": "crytic-compile",
		"platformConfig": {
			"target": ".",
			"solcVersion": "",
			"exportDirectory": "",
			"args": []
		}
	},
	"logging": {
		"level": "info",
		"logDirectory": ""
	}
}%
`

Just run the official [rep code](https://github.com/crytic/secureum-medusa.git), ERC20Test.sol example.

How long this example will last normally?

**Comment by elopez** [comment]
@yuliyu123 hi! can you please check in the "Console" macOS application (![Screenshot 2023-08-17 at 12 47 57](https://github.com/crytic/medusa/assets/2642849/5d0a0419-b890-493f-937d-5905bee9a93f)) to see if there are any logs related to the crash? If so, can you provide them here?

**Comment by yuliyu123** [comment]
> 

hi elopez, no useful log in the "Console" application, maybe killed by the system, and it always crash after run about 20 minutes. Maybe it's not compatible with M1 mac?

**Comment by elopez** [comment]
@yuliyu123 M1 should be supported fine from what I understand. Did you install medusa by building from source, or did you get a binary from the releases page? If you are using a binary, did you download the native one for M1 (`medusa-mac-arm64.zip` download) or Intel Mac (`medusa-mac-x64.zip` download)? You can also run `file $(which medusa)` in a terminal to see what kind of binary you have.

Could you also check in "Activity Monitor" while medusa is running and see if you notice a pattern in resource usage (e.g. medusa using increasing amounts of memory until it fails, or something like that?) This would help to tell if what we're seeing is a memory leak somewhere.

**Comment by yuliyu123** [comment]
yeah, the CPU and memory resource occupation is very high when running the fuzz test cases. I installed it by building from source. Binary format: `/usr/local/bin/medusa: Mach-O 64-bit executable arm64`.

CPU status: `PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP
23182  medusa       544.0 01:36.18 14/5   0    35    1159M+ 0B     0B     23182
18310  forge        98.0  18:55.89 19/1   1    70    161M+  0B     23M    18310`

**Comment by yuliyu123** [comment]
> @yuliyu123 coming back to this since it seems like medusa might have a memory management issue. Do you have the code that caused this to occur? Was it your submission for the secureum workshop?

I just used this tool to learn fuzz test, and run [this repo](https://github.com/crytic/secureum-medusa) ERC20Test.sol example. It seems this tool has a memory management issue before.

**Comment by yuliyu123** [comment]
> > @yuliyu123 coming back to this since it seems like medusa might have a memory management issue. Do you have the code that caused this to occur? Was it your submission for the secureum workshop?
> 
> I just used this tool to learn fuzz test, and run [this repo](https://github.com/crytic/secureum-medusa) ERC20Test.sol example. It seems this tool has a memory management issue before.

Maybe we can use flame graph to analyze the memory usage.

**Comment by anishnaik** [comment]
Closed by #290
