### ISSUE TITLE
Feature request: Open all non-zero coverage reports by default

### ISSUE THREAD

**Issue by aviggiano** [crytic/medusa#233]
Hello,

During the debugging process, a common step involves referencing the coverage report multiple times to determine why the fuzzer isn't hitting certain lines.

Although Medusa's report offers a superior user experience when compared to Echidna, in general, it is still somewhat inconvenient that we have to `Cmd+R` to refresh and reopen the target contracts every time. Trying to find a specific line using `Cmd+F` is ineffective since all dropdowns are minimized.

I suggest that reports with more than 0% coverage should automatically open in the HTML.

There might be a more intuitive way to directly access what one is looking for (which often begins with the target contract, but not always). However, I am not sure how to do it, which is why I believe this feature request is a good first step.

**Comment by aviggiano** [comment]
If you agree with this feature I can try implementing it

**Comment by anishnaik** [comment]
Hey @aviggiano this is something I have found to be a problem with our coverage reports as well. I think this is a worthwhile feature to have. It is important to note that the output will initially be a lot more verbose for large projects that have large inheritance structures and so on. I think the tradeoff is worthwhile though.

Would love for you to take a stab at implementing this. Please reach out to me if you need any pointers on how to approach this :)

**Comment by anishnaik** [comment]
Closed by #243
