### ISSUE TITLE
Timestamp and block number start very low

### ISSUE THREAD

**Issue by rappie** [crytic/medusa#235]
I'm logging the timestamp and block numbers here:
```
 => [event] Debug0("block.timestamp", 2)
 => [event] Debug0("block.number", 2)
```

This causes a problem for my fuzzing setup because I want to schedule events in the past, which gives me an underflow if I try to calculate them.

I've tried using the `warp` and `roll` cheatcodes in the constructor but got the following error:
```
error Failed to initialize the test chain
‣ contract deployment tx returned a failed status: execution reverted
```

**Comment by anishnaik** [comment]
Hey @rappie sorry for the delay in reaching out. Are you trying to `warp` or `roll` in the constructor?

**Comment by rappie** [comment]
Yes
