### ISSUE TITLE
Failed to compile target: unable to parse init bytecode for contract '...'

### ISSUE THREAD

**Issue by 0xpolarzero** [crytic/medusa#266]
I'm stumbling into this error when trying to run Medusa on a project. Weirdly, it will not always fail to parse the bytecode from the same contract

Logs:
```sh
$ medusa --config test/fuzzing/medusa/config.json fuzz
⇾ Reading the configuration file at: test/fuzzing/medusa/config.json
⇾ Compiling targets with crytic-compile
error Failed to compile target
‣ unable to parse init bytecode for contract 'UnstakeTest'
```

Another time it will be:
```sh
...
‣ unable to parse init bytecode for contract 'PausingTest'
```

---

I can however compile the contracts, with either `forge build` or `crytic-compile .`, with no issue at all. Only when trying to run the fuzzing campaign, this happens.

The contracts failing to be compiled (or at least to be parsed) are actually not used during the campaign. But I could not find an argument to pass to crytic-compile, so it could just ignore some directory—is there any?

I don't really have any additional information to give. It's based on [Mantle LSP contracts](https://github.com/mantle-lsp/contracts/tree/main)—the ones failing to compile are some of their tests.

Here is my Medusa [configuration file](https://github.com/0xpolarzero/mantle-lsp-fuzzing-formal-verification/blob/main/test/fuzzing/medusa/medusa.json).
The contracts failing to compile: [UnstakeTest](https://github.com/0xpolarzero/mantle-lsp-fuzzing-formal-verification/blob/main/test/Staking.t.sol#L736); [PausingTest](https://github.com/0xpolarzero/mantle-lsp-fuzzing-formal-verification/blob/b0dcf296a81106e08a4944e1d13fa6f963fb41a0/test/Integration.t.sol#L151).

---

P.S. The tests are not actually expected to run successfully, since it requires an initial contract's balance, and from my understanding it's not yet available with Medusa. I just copied and adapted them from an Echidna project, so it can be ready for later.

**Comment by anishnaik** [comment]
Hey @0xpolarzero thanks for bringing this up. We will take a look at it in the next few days.

**Comment by peppelan** [comment]
FYI @0xpolarzero I had the same issue & could work around it by adding the "--compile-libraries" [in analogy to this suggestion](https://github.com/crytic/echidna/issues/651#issuecomment-1648400908).

I believe it's to be attributed to crytic-compile rather than medusa. [There was an update regarding this in crytic-compile 3.3.4](https://github.com/crytic/crytic-compile/issues/476#issuecomment-1669700516) but I still had this issue with 3.3.5.

It may apply to you as well if your project has libraries. Bonne année!

**Comment by 0xpolarzero** [comment]
@peppelan This worked perfectly! Thanks a lot.

Bonne année à toi aussi!

---

For reference:

These are the contracts that were making the test fail:
```solidity
// Staking.sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

...
// vvv Libraries
import {Math} from "openzeppelin/utils/math/Math.sol";
import {SafeERC20Upgradeable} from "openzeppelin-upgradeable/token/ERC20/utils/SafeERC20Upgradeable.sol";

// Staking.t.sol

...
// vvv Library
import {SignerUtils} from "./utils/SignerUtils.sol";
```

I just changed `config.json` to:

```json
{
  ...
  "compilation": {
    "platform": "crytic-compile",
    "platformConfig": {
      ...
      "args": [
        "--compile-libraries=(Math,0xf01),(SafeERC20Upgradeable,0xf02),(SignerUtils,0xf03)"
      ]
    }
  },
}
```
