### ISSUE TITLE
Feature Request: Support Initial ETH balance 

### ISSUE THREAD

**Issue by algobotishere** [crytic/medusa#282]
Feature Request: Configuration Options for Contract Balances

`contractBalance`: Sets the balance of the contract under test. Essential for functions where contract balance impacts behavior.

**Comment by anishnaik** [comment]
Hey @algobotishere - thanks for opening an issue. We have this PR #216 that will integrate this feature (there is a minor bug with it which I will fix this week). Also, we already have an open issue about this at #213 so will close this one.
