### ISSUE TITLE
Crash after removing a function that is still in the corpus

### ISSUE THREAD

**Issue by rappie** [crytic/medusa#287]
After removing a function from the code that is still in the corpus, in some cases this error happens:

![image](https://github.com/crytic/medusa/assets/1430820/4658d420-b6f3-4d67-bba8-d84407476ec9)

**Comment by anishnaik** [comment]
Hey @rappie thanks for calling this out. Seems like we should not be throwing an error here and I believe that somehow this has entered a codepath that it should not when in fact that corpus element will be thrown out.

Will mark this as a bug.

**Comment by anishnaik** [comment]
Hey @rappie after some more thought this seems like the correct behavior...If there was a function that was removed from the codebase but still exists in the corpus, it should throw an error. Would you prefer that medusa "disable" the element in case the method is no longer found?

**Comment by rappie** [comment]
I believe ignoring the sequence with incorrect function calls would be the best compromise between the amount of work and user friendliness.

If you decide to throw an error, there should be a more descriptive error text that explains the reason (ideally with the function name and not the `4byte`). It would also be nice to have some option to remove it from the corpus on disk so you can keep using the corpus.

**Comment by anishnaik** [comment]
Noted, thanks @rappie . Will think about the best tradeoff here and get back to you on this thread.
