### ISSUE TITLE
`medusa fuzz` exits with code 0 when an error is found

### ISSUE THREAD

**Issue by aviggiano** [crytic/medusa#289]
This is not expected, and is different than the behavior of Echidna

# Medusa

```
git clone https://github.com/aviggiano/shrinking-mwe
cd shrinking-mwe
medusa fuzz 1>/dev/null
echo $?
> 0
```

# Echidna

```
git clone https://github.com/aviggiano/shrinking-mwe
cd shrinking-mwe
echidna . --contract CryticTester --config echidna.yaml 1>/dev/null
echo $?
> 1
```

**Comment by anishnaik** [comment]
@aviggiano are you saying that running `shrinking-mwe`'s fuzz suite results in an error and in the case of an error medusa throws an exit code of zero instead of one?

Just want to make sure I'm on the same page.

**Comment by aviggiano** [comment]
> @aviggiano are you saying that running `shrinking-mwe`'s fuzz suite results in an error and in the case of an error medusa throws an exit code of zero instead of one?
> 
> Just want to make sure I'm on the same page.

Exactly. When finding an error, I was expecting the exit code to be 1

**Comment by anishnaik** [comment]
@aviggiano what is the exact error that medusa/echidna is throwing? Based on the code I am seeing:
```func main() {
	// Run our root CLI command, which contains all underlying command logic and will handle parsing/invocation.
	err := cmd.Execute()

	if err != nil {
		os.Exit(1)
	}
}
```

Medusa should throw an exit code of 1 if there is an error. Maybe there is a code path that I am missing where the exit code is zero?

**Comment by anishnaik** [comment]
Also, do you mind expanding as to what you mean by "error"? Is the "error" a failing test case or the error is a "program error"?

**Comment by aviggiano** [comment]
> Medusa should throw an exit code of 1 if there is an error. Maybe there is a code path that I am missing where the exit code is zero?

well, I'm getting an unexpected exit code, see:

```
shrinking-mwe on  main [?] via slither
[I] ➜ medusa fuzz
⇾ Reading the configuration file at: shrinking-mwe/medusa.json
⇾ Compiling targets with crytic-compile
warn Currently, optimization mode's call sequence shrinking is inefficient; this may lead to minor performance issues
⇾ Creating 10 workers...
⇾ fuzz: elapsed: 0s, calls: 0 (0/sec), seq/s: 0, coverage: 9
⇾ Fuzzer stopped, test results follow below ...
⇾ [FAILED] Property Test: CryticTester.invariant()
Test for method "CryticTester.invariant()" failed after the following call sequence:
[Call Sequence]
1) CryticTester.setNumber(3) (block=28584, time=176362, gas=12500000, gasprice=1, value=0, sender=0x0000000000000000000000000000000000010000)
[Execution Trace]
 => [call] CryticTester.setNumber(3) (addr=0xA647ff3c36cFab592509E13860ab8c4F28781a66, value=0, sender=0x0000000000000000000000000000000000010000)
	 => [return ()]

[Property Test Execution Trace]
[Execution Trace]
 => [call] CryticTester.invariant() (addr=0xA647ff3c36cFab592509E13860ab8c4F28781a66, value=0, sender=0x0000000000000000000000000000000000010000)
	 => [return (false)]

⇾ Test summary: 0 test(s) passed, 1 test(s) failed
⇾ Coverage report saved to file: medusa/coverage_report.html

shrinking-mwe on  main [?] via slither took 3s
[I] ➜ echo $?
0
```

> Also, do you mind expanding as to what you mean by "error"? Is the "error" a failing test case or the error is a "program error"?

By "error" I mean a failing test case. I would expect the program to exit with code 1 when a failing test case is found.

**Comment by anishnaik** [comment]
To be honest, I am not sure we want to throw an exit code of 1 if a test case fails. The way I am thinking through this is a failing test case still means that medusa executed "successfully". Like nothing went wrong in medusa's fuzzing cycle. There was a broken invariant but in some ways that means medusa did its job correctly. I would say an exit code of one should be thrown if something like compilation fails or there is a bug in our fuzzing loop.

So, I am not completely sure we want to fix this behavior? Personally, I am fine with this deviation from Echidna but would love to your thoughts.

**Comment by aviggiano** [comment]
> To be honest, I am not sure we want to throw an exit code of 1 if a test case fails.

Well, I think this is standard for [GNU/Linux programs](https://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux), which is why I said it was the "expected behavior".

For example:

*`grep` exits with code 1 when the string is not found*

```
shrinking-mwe on  main [?] via slither
[I] ➜ grep INVALID_STRING medusa.json

shrinking-mwe on  main [?] via slither
[I] ➜ echo $?
1
```

*`find` exits with code 1 when the file/directory is not found*

```
shrinking-mwe on  main [?] via slither
[I] ➜ find . '*INVALID_FILE*' -type d -d 1
./crytic-export
./cache
./test
./out
./medusa
./script
./echidna
./.github
./lib
./.git
./src
find: *INVALID_FILE*: No such file or directory

shrinking-mwe on  main [?] via slither
[I] ➜ echo $?
1
```

*`forge` exits with code 1 when a test case fails*

```
shrinking-mwe on  main [?] via slither took 12s
[I] ➜ forge test
[⠆] Compiling...
[⠒] Compiling 23 files with 0.8.24
[⠰] Solc 0.8.24 finished in 3.90s
Compiler run successful!

Running 3 tests for test/Counter.t.sol:CounterTest
[FAIL. Reason: <empty revert data>]
	[Sequence]
		sender=0x97ACB6CfAeb6BD834CC8b49e21B7D40C66972c5d addr=[src/Counter.sol:Counter]0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f calldata=setNumber(uint256) args=[3]
 invariant() (runs: 256, calls: 3826, reverts: 262)
[PASS] testFuzz_SetNumber(uint256) (runs: 256, μ: 27954, ~: 28499)
[PASS] test_Increment() (gas: 28458)
Test result: FAILED. 2 passed; 1 failed; 0 skipped; finished in 317.39ms

Ran 1 test suites: 2 tests passed, 1 failed, 0 skipped (3 total tests)

Failing tests:
Encountered 1 failing test in test/Counter.t.sol:CounterTest
[FAIL. Reason: <empty revert data>]
	[Sequence]
		sender=0x97ACB6CfAeb6BD834CC8b49e21B7D40C66972c5d addr=[src/Counter.sol:Counter]0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f calldata=setNumber(uint256) args=[3]
 invariant() (runs: 256, calls: 3826, reverts: 262)

Encountered a total of 1 failing tests, 2 tests succeeded

shrinking-mwe on  main [?] via slither took 6s
[I] ➜ echo $?
1
```

Having a different exit code for when a test case fails is useful for automation. For example, if I want to create a [bash script to detect if an invariant](https://github.com/aviggiano/fuzzer-evaluation/blob/main/evaluate.sh#L47) was found. Otherwise, I'd need to `grep` the output. 

An alternative solution, albeit less preferred in my opinion, is to provide a `--fail-on-test-case` sort of flag that can achieve this outcome. For example, linters usually do that that: `solhint --max-warnings 0` or `forge fmt --check`

**Comment by anishnaik** [comment]
Okay totally fair argument - @Xenomega what do you think? This seems pretty reasonable. Will have to discuss how to best implement it.

**Comment by Xenomega** [comment]
I can add this now with an exit code that specifically distinguishes failed test cases =)
