### ISSUE TITLE
Files with no coverage should be marked 0%

### ISSUE THREAD

**Issue by damilolaedwards** [crytic/medusa#296]
In the coverage report generated during fuzzing, if a file has no coverage (e.g interfaces), medusa calculates a 100% coverage for the file since 0/0 = 100%. In this case it should be marked 0%
![sample](https://github.com/crytic/medusa/assets/19494452/11bebcba-65cc-4957-a5fd-4be92b3c2af1)

**Comment by anishnaik** [comment]
Agreed :) This PR should solve it
https://github.com/crytic/medusa/pull/216
