### ISSUE TITLE
Add logs format option

### ISSUE THREAD

**Issue by aviggiano** [crytic/medusa#316]
I'd like to create a chart of medusa's run over time. 

For example, this can be useful to grasp how coverage is increasing as time passes.

One solution could be to have a "log output format" option, so that I can setup `csv` and instead of printing:

```
fuzz: elapsed: 3s, calls: 4122 (1373/sec), seq/s: 14, coverage: 102
fuzz: elapsed: 6s, calls: 6048 (641/sec), seq/s: 6, coverage: 105
fuzz: elapsed: 9s, calls: 6473 (141/sec), seq/s: 1, coverage: 105
```

it could print

```
elapsed,calls,calls_per_sec,seq_per_s,coverage
3,4122,1373,14,102
6,6048,641,6,105
9,6473,141,1,105
```

**Comment by 0xalpharush** [comment]
It is pretty straightforward to extract this info with regex from the log. The tracking of unique PC's was added here but we may not always use or track this metric https://github.com/crytic/medusa/commit/ff587c3d49001f0399a32fdba36b131d5a59a334

**Comment by aviggiano** [comment]
True, I don't think this feature is useful enough to be included on the fuzzer
