### ISSUE TITLE
Add M1 build image support to CI/CD

### ISSUE THREAD

**Issue by Xenomega** [crytic/medusa#317]
Our CI/CD currently builds for the following platforms:
- Linux (x86-64)
- mac OS (x86-64)
- Windows (x86-64)

It does not build:
- mac OS (ARM64)

Adding a runner for this that builds M1 images will streamline the release process. It's not necessary for running tests, however.

**Comment by 0xalpharush** [comment]
https://github.com/crytic/medusa/pull/342
