### ISSUE TITLE
CLI warning on `go build` for malformed/unidentified symbol

### ISSUE THREAD

**Issue by 0xicingdeath** [crytic/medusa#331]
After building Medusa from source and running `go build`, getting the following warning: 

```
# github.com/crytic/medusa
ld: warning: '/private/var/folders/68/r6z4l86d0zn8qy8hb48bd8fh0000gp/T/go-link-3501725939/go.o' has malformed LC_DYSYMTAB, expected 127 undefined symbols to start at index 27562, found 170 undefined symbols starting at index 121
```

On an M2 computer, aarm arch

**Comment by anishnaik** [comment]
Yea i've been getting this for a while and hasn't really affected my usage of it. Let's keep the issue open in case it triggers something down the line.

**Comment by 0xicingdeath** [comment]
I haven't noticed anything from it either! Just cleaning out loose ends from notes I took while using on Curvance 😛

**Comment by Xenomega** [comment]
Just for more information, this seems to be a non-issue, and not a problem on our end:
- https://github.com/golang/go/issues/61229
- https://github.com/golang/go/issues/61558
