### ISSUE TITLE
Print error if unsupported flag is provided

### ISSUE THREAD

**Issue by bohendo** [crytic/medusa#334]
```
$ medusa --version
medusa version 0.1.3

$ medusa fuzz --target flags.sol 

$ echo $?
1
```

If I pass the depreciated `--target` flag to the latest medusa, it will do nothing unsuccessfully. If we wanted to get fancy, we could print a custom error message for depreciated flags nudging users towards the new ones. But we should at least print a generic warning if medusa failed because it got a flag it didn't recognize.

**Comment by elopez** [comment]
This should be addressed by https://github.com/crytic/medusa/pull/312
