### ISSUE TITLE
contract deployment tx returned a failed status: execution reverted

### ISSUE THREAD

**Issue by aviggiano** [crytic/medusa#351]
I am trying to run medusa on a codebase but it is failing with the following error:

```
[I] ➜ medusa fuzz
⇾ Reading the configuration file at: medusa.json
⇾ Compiling targets with crytic-compile
error Failed to initialize the test chain
‣ contract deployment tx returned a failed status: execution reverted
```

The same codebase works with Echidna

Unfortunately, it is still private, but I'd like to know if there are any recommendations on how to debug this issue. Is there a verbose/debug mode that I can use to understand why it is failing?

**Comment by 0xicingdeath** [comment]
Have you tried using the coverage report to see what lines of the constructor are failing? I found Medusa's report to be pretty accurate for tracking what lines of the constructor ended up executing or reverting.

**Comment by 0xalpharush** [comment]
Can you try the `master` branch? It should have better error reporting 
https://github.com/crytic/medusa/pull/337
