### ISSUE TITLE
Medusa 0.1.5 performance issues vs 0.1.3

### ISSUE THREAD

**Issue by GalloDaSballo** [crytic/medusa#414]
All benchmarks done via Docker, with base image: `ubuntu:20.04`

It seems like the latest changes to Medusa make it so that it is slower in raising coverage

This appears to be less evident for smaller codebases but more apparent when dealing with more complex codebases

Here's a direct comparison done on eBTC:
Medusa 0.1.3 get's to 100 pretty fast: https://staging.getrecon.xyz/shares/c437d326-d059-48af-9de3-890c01f7bddc
Medusa 0.1.5 remains stuck at 50/60 for a bit: https://staging.getrecon.xyz/shares/653134fc-ae02-48bd-80bc-ca61628f8c8a

Another comparison:
Medusa 0.1.5 stuck at 45: https://staging.getrecon.xyz/shares/7c08cfcc-9e63-4d69-b26d-1cdfcab9e742
Medusa 0.1.3 get's to 100 very quickly: https://getrecon.xyz/dashboard/jobs/47ba31d6-8eed-4c6b-9792-b9ed39c371af

Link to branches are in the links above (scroll to Stats for Nerds)

**Comment by 0xalpharush** [comment]
We are investigating this.Would you mind running with `{"testViewMethods": false}` and seeing how that affects per https://github.com/euler-xyz/euler-vault-kit/blob/20973e1dd2037d26e8dea2f4ab2849e53a77855e/medusa.json#L36?

**Comment by GalloDaSballo** [comment]
> We are investigating this. Would you mind running with `{"testViewMethods": false}` and seeing how that affects perf https://github.com/euler-xyz/euler-vault-kit/blob/20973e1dd2037d26e8dea2f4ab2849e53a77855e/medusa.json#L36?

Have queued a job here, it updates every minute and should be comparable in 15:
https://staging.getrecon.xyz/shares/ff11b245-d03f-49c9-adbb-af60c6f1d326

**Comment by 0xalpharush** [comment]
At a glance, it does seem like call/s is higher in 0.1.5 or am I mistaken? Will you try https://github.com/crytic/medusa/pull/415 as well. Not including calls to property tests in the call sequences may reduce the number of entries in the corpus (as does not calling view functions as you pointed out). So comparing the two counts between versions may not be useful, but this is just a hunch

**Comment by GalloDaSballo** [comment]
> At a glance, it does seem like call/s is higher in 0.1.5 or am I mistaken? Will you try #415 as well? Not including calls to property tests in the call sequences may reduce the number of entries in the corpus (as does not calling view functions as you pointed out). So comparing the two coverage counts between versions may not be useful (as opposed to the % covered of the actual code being tested), but this is just a hunch

I think the 39 we're seeing is equivalent to the 45 we were getting before due to the reduce number of tests

Have stopped the job so you can grab the coverage report (you can also download the /medusa folder by clicking "download corpus")

Running the repo on 0.1.3 should net massively higher coverage (85+) in a matter of seconds

**Comment by GalloDaSballo** [comment]
20+ minutes (link shared above)
<img width="708" alt="Screenshot 2024-07-25 at 15 11 01" src="https://github.com/user-attachments/assets/e2291c21-5d82-434f-a797-40d480104003">

1 minute (0.1.3 locally)
<img width="726" alt="Screenshot 2024-07-25 at 15 11 26" src="https://github.com/user-attachments/assets/b66879eb-a170-4db9-b69c-fb6492e1e528">

**Comment by GalloDaSballo** [comment]
> At a glance, it does seem like call/s is higher in 0.1.5 or am I mistaken? Will you try #415 as well? Not including calls to property tests in the call sequences may reduce the number of entries in the corpus (as does not calling view functions as you pointed out). So comparing the two coverage counts between versions may not be useful (as opposed to the % covered of the actual code being tested), but this is just a hunch

We can try running from #415 but we'll need a while to provision new docker images

**Comment by GalloDaSballo** [comment]
Maybe a bit early to tell but the numbers does look better after building from #415 
https://staging.getrecon.xyz/shares/4c26ba47-284a-43d1-9704-aceae4ee4384
