### ISSUE TITLE
Errors using medusa with crytic-compile: `unable to parse ABI` & `unable to parse init bytecode`

### ISSUE THREAD

**Issue by blablalf** [crytic/medusa#439]
Hello,

I am using `crytic-compile` to compile the contracts. While I run `crytic-compile` command alone I don't get any error:
```
crytic-compile --compile-force-framework foundry --compile-libraries="(Lib1,0xf0),(Lib2,0xf1),(Lib3,0xf2),(Lib4,0xf3),(Lib5,0xf4),(Lib6,0xf5),(Lib7,0xf6),(Lib8,0xf7),(Lib9,0xf8),(Lib10,0xf9)" --foundry-compile-all .

INFO:CryticCompile:'forge clean' running (wd: /home/blablalf/project-root)
INFO:CryticCompile:'forge build --build-info' running (wd: /home/blablalf/project-root)
```

But when I use medusa I get some errors:
```
npm run medusa

> @orga/project-root@0.17.1 medusa
> medusa fuzz --config test/fuzzing/config/medusa.json

⇾ Reading the configuration file at: test/fuzzing/config/medusa.json
⇾ Compiling targets with crytic-compile
error Failed to compile target
‣ unable to parse ABI for contract 'Lib7'
```  

So I tried to remove the `--compile-libraries` arg of `platformConfig/args` and I got a new error:
```
npm run medusa

> @orga/project-root@0.17.1 medusa
> medusa fuzz --config test/fuzzing/config/medusa.json

⇾ Reading the configuration file at: test/fuzzing/config/medusa.json
⇾ Compiling targets with crytic-compile
error Failed to compile target
‣ unable to parse init bytecode for contract 'RandomContract'
```
The `RandomContract` is different each time I run the command.

Here is my medusa config:
```
{
	"fuzzing": {
		"workers": 8,
		"shrinkLimit": 5000,
		"callSequenceLength": 30,
		"corpusDirectory": "medusa_assert_corpus",
		"targetContracts": ["FuzzingSuite"],
		"deployerAddress": "0x10000",
		"senderAddresses": [
			"0x20000"
		],
		"testing": {
			"assertionTesting": {
				"enabled": true
			},
			"propertyTesting": {
				"enabled": false
			},
			"optimizationTesting": {
				"enabled": false
			}
		},
		"chainConfig": {
			"codeSizeCheckDisabled": true,
			"cheatCodes": {
				"enableFFI": true
			}
		}
	},
	"compilation": {
		"platform": "crytic-compile",
		"platformConfig": {
			"args": [
				"--compile-force-framework", "foundry",
				"--compile-libraries=(Lib1,0xf0),(Lib2,0xf1),(Lib3,0xf2),(Lib4,0xf3),(Lib5,0xf4),(Lib6,0xf5),(Lib7,0xf6),(Lib8,0xf7),(Lib9,0xf8),(Lib10,0xf9)",
				"--foundry-compile-all"
			],
			"exportDirectory": "../../../crytic-export",
			"target": "../../../."
		}
	},
	"logging": {
		"level": "info",
		"logDirectory": ""
	}
}
```

Thanks for any time you will take for this.

**Comment by blablalf** [comment]
> Based off #266, I would guess that there is a library that isn't being linked and the placeholder can't be decode as hex. Could you run `crytic-compile --print-libraries .` and make sure all the listed libraries are in the list provided to `--compile-libraries` (paste the output of the command here too please)?
> 
> Also, what version of Medusa are you using?

Hey, thank this issue linking, it confirms me that the `--compile-libraries` is indeed necessary.

I ran the `crytic-compile --print-libraries .` command. I therefore added potentially missing libs to `--compile-libraries` arg.
Unfortunatly I am back to the following error:
```
‣ unable to parse ABI for contract 'Lib7'
```
I understand that I just made a step back by trying to compile without `--compile-libraries` arg.

These two issues seem unlinked to me.

Unfortunatly I cannot share the output of the command for privacy related reasons but I'm using `medusa version 0.1.6`.

**Comment by anishnaik** [comment]
Hey @blablalf, is it possible that `Lib7` depends on another external library?

**Comment by blablalf** [comment]
> Hey @blablalf, is it possible that `Lib7` depends on another external library?

Hey @anishnaik, thank you for your reply.
Yes, indeed, it depends on six other libs.

**Comment by anishnaik** [comment]
Oh, I do remember dealing with this issue before. This is because the `go-ethereum` ABI library we use cannot parse the ABI of external libraries. I cannot remember the exact reason but for some reason the ABI representation is different. 

We are hoping that resolving #63 will help in resolving this concern.

**Comment by blablalf** [comment]
> Oh, I do remember dealing with this issue before. This is because the `go-ethereum` ABI library we use cannot parse the ABI of external libraries. I cannot remember the exact reason but for some reason the ABI representation is different.
> 
> We are hoping that resolving #63 will help in resolving this concern.

Very interesting thank you for the explanation. Do you think there is something I can do to move forward about this apart from not using external libs? From what I understand [#63](https://github.com/crytic/medusa/issues/63) will not be resolved before a long time.

**Comment by anishnaik** [comment]
Although this is not ideal, you may have to change the source code of the libraries so that all function definitions are `internal`. This will remove the requirement that the libraries need to be deployed .

**Comment by anishnaik** [comment]
Can you paste the `testChainConfig` portion of your medusa configuration? You should technically not be hitting this error:
`vm error ('out of gas: max initcode size exceeded: size 90398')`

**Comment by blablalf** [comment]
> "chainConfig": {
> 			"codeSizeCheckDisabled": true,
> 			"cheatCodes": {
> 				"enableFFI": true
> 			}
> 		}

Hey, thank you for your reply. Here it is:
```
"chainConfig": {
  "codeSizeCheckDisabled": true,
  "cheatCodes": {
    "enableFFI": true
  }
}
```
