### ISSUE TITLE
medusa appears to use one more core than specified

### ISSUE THREAD

**Issue by elopez** [crytic/medusa#470]
When running medusa with `--workers 4` I observe the tool saturates 5 cores, not 4. I would expect it to use just 4 cores.

**Comment by rappie** [comment]
Do you have `symExec` disabled?

**Comment by elopez** [comment]
medusa does not have `symExec` as far as I recall 😅 

As a sort of workaround, `GOMAXPROCS=4` can be exported on the environment to limit the CPU use to just 4 threads.

**Comment by rappie** [comment]
Ah right, I got confuzzled with the repo name :smile:

**Comment by 0xalpharush** [comment]
I don't think we plan on fixing this as workers == # of goroutines (and the Go runtime does what it can with available resources) and the workaround provided is sufficient IIUC
