### ISSUE TITLE
Periodically generate calls to view methods in the CallSequence

### ISSUE THREAD

**Issue by Xenomega** [crytic/medusa#55]
We'll want to periodically call view methods to increase coverage. Additionally, assertion testing supports config-driven options to enable assert testing of view methods, but the `FuzzerWorker` only produces `CallSequence`s with calls targeting state changing methods right now, so it's never hit.

Requirements:
- Record view functions separately, but alongside the existing `stateChangingMethods` (see the `updateStateChangingMethods` method)
- Add a really low probability of sourcing a target method from it (instead of `stateChangingMethods`) at the top of the `generateFuzzedCall` method.
- Ensure the `corpus.UpdateCorpusAndCoverageMaps` method checks if the last call was to a view method. If it was, do not record the call sequence in the corpus at that step, as it's not a coverage-increasing sequence we'd be interested in recording, as it was not state changing.

**Comment by Jaime-Iglesias** [comment]
Will try to pick this up starting tomorrow.

**Comment by 0xalpharush** [comment]
>Ensure the corpus.UpdateCorpusAndCoverageMaps method checks if the last call was to a view method. If it was, do not record the call sequence in the corpus at that step, as it's not a coverage-increasing sequence we'd be interested in recording, as it was not state changing.

need clarification on this but https://github.com/crytic/medusa/pull/363 addresses the other points

**Comment by ggrieco-tob** [comment]
I think view functions should be part of the coverage, in particular if they have or can contain assertions.
