### ISSUE TITLE
Add CODEOWNERS

### ISSUE THREAD

**Issue by Xenomega** [crytic/medusa#64]
We should add a [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to enforce PR review by specific parties.

Me and @anishnaik should be one of those CODEOWNERS for now, as e.g. I have a lot of notions about how code should evolve and probably some undocumented considerations for why some code should look specifically as it does (so it can support future features we may not have now), that we don't want to step on. This will evolve with more people as we onboard everyone :)

**Comment by ggrieco-tob** [comment]
Closed by #141
