### ISSUE TITLE
Logging improvements (display version on start, add quiet/verbose options)

### ISSUE THREAD

**Issue by ahpaleus** [crytic/medusa#93]
The issue with gathering UX improvements and initial ideas:
- [ ] quiet option to hide stderr from solc, etc. 
- [x] make UI more colorful/transparent
- [ ] medusa's version in the visible place (at the start?)

**Comment by Xenomega** [comment]
A lot of this is being handled within #95, so I rescoped this issue. I updated the checkmarks above to reflect the current status.
